#!/usr/bin/osascript

on run (arguments)
	tell application "Adobe InDesign CS6"
		set myDocument to open (first item of arguments) without showing window
		tell myDocument to make window
		tell active document
			export format EPUB to (second item of arguments) without showing options
		end tell
	end tell
end run

